# Generated by Django 5.0 on 2023-12-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fr_content', models.CharField(max_length=255)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
