# Generated by Django 5.0 on 2023-12-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_regions', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Qoraqalpog\\iston Respublikasi', 'Qoraqalpog\\iston Respublikasi'), ('Farg\\ona', 'Farg\\ona'), ('Namangan', 'Namangan'), ('Andijon', 'Andijon'), ('Jizzax', 'Jizzax'), ('Sirdaryo', 'Sirdaryo'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Navoiy', 'Navoiy'), ('Xorazm viloyati', 'Xorazm viloyati')], max_length=255)),
                ('post_title', models.CharField(max_length=255)),
                ('fr_content', models.TextField()),
                ('post_image', models.TextField()),
                ('post_hashtag', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='fr_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
    ]
